# Numpy in Python for Data Science

### NumPy (Numerical Python)

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

The NumPy library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

### Difference between a Python list and a NumPy array?

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

**Why use NumPy?**

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

## Section 3.1: Arrays & It's Types

>*An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element.*
1.  A vector is an array with a single dimension (there’s no difference between row and column vectors)
2.  A matrix refers to an array with two dimensions
3.  For 3-D or higher dimensional arrays, the term tensor is also commonly used

### 3.1.1: 1-D Arrays

In [ ]:
import numpy as np

a = np.array([5, 5, 5,])
a

array([5, 5, 5])

In [ ]:
a = np.array([2,4,6,8,10])
a

array([ 2,  4,  6,  8, 10])

In [ ]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
b = np.zeros(3)
b

array([0., 0., 0.])

In [ ]:
c = np.ones(4)
c

array([1., 1., 1., 1.])

>Create an empty array with 3 elements

In [ ]:
d = np.empty(3)
d

array([0., 0., 0.])

>Creating array with range of elements

In [ ]:
e = np.arange(9)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

> Creating array between specific range of elements

In [ ]:
f = np.arange(1, 15)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

> Creating array between specific range of elements and specified interval (5)


In [ ]:
g = np.arange(50, 100, 5)
g

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

> Linearly spaced arrays

In [ ]:
h = np.linspace(100 , 120, num= 5)
h

array([100., 105., 110., 115., 120.])

> specific data types in array

In [ ]:
i = np.ones(5, dtype = np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [ ]:
j = np.ones(4, dtype = np.float64)
j

array([1., 1., 1., 1.])

### 3.1.2: 2-D Arrays

In [ ]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.zeros((5,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
c = np.empty((3,3))
c

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.29049947e-320],
       [8.34441742e-308, 9.79107192e-307, 3.33509775e-317]])

### 3.1.3: 3-D Arrays

In [ ]:
x = np.array([[[1,2,3,4], [2,3,4,5], [9,8,7,6]], [[7,8,9,4], [1,4,7,8], [1,5,9,7]], [[4,5,6,8], [3,2,1,4], [2,5,4,8]]])
x

array([[[1, 2, 3, 4],
        [2, 3, 4, 5],
        [9, 8, 7, 6]],

       [[7, 8, 9, 4],
        [1, 4, 7, 8],
        [1, 5, 9, 7]],

       [[4, 5, 6, 8],
        [3, 2, 1, 4],
        [2, 5, 4, 8]]])

>making and reshaping a 3D array

In [ ]:
a = np.arange(60).reshape(3,4,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

## Section 3.2: Array Functions

In [ ]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

### 3.2.1 Sorting of one 1-D Array

In [ ]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

### 3.2.2 Type of Array

In [ ]:
type(a)

numpy.ndarray

### 3.2.3 Length of an array

In [ ]:
len(a)

10

In [ ]:
b = np.array([10.2, 3.4, 5.3, 35.2, 45.2])
b

array([10.2,  3.4,  5.3, 35.2, 45.2])

### 3.2.4 Concatenation of Array

> Concatenation of 1-D Array

In [ ]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,   5.3,  35.2,  45.2])

In [ ]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   5.3,   6. ,  10. ,  10.2,  10.3,
        12. ,  15. ,  35.2,  45.2, 100. , 320. ])

> Concatenation of 2-D Array

In [ ]:
a = np.array([[1,2,3,4,5], [5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [ ]:
b = np.array([[6,7,5,6,6], [8,9,5,9,5]])
b

array([[6, 7, 5, 6, 6],
       [8, 9, 5, 9, 5]])

In [ ]:
c = np.concatenate((a,b))
c

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [6, 7, 5, 6, 6],
       [8, 9, 5, 9, 5]])

In [ ]:
c = np.concatenate((a,b), axis=1)
c

array([[1, 2, 3, 4, 5, 6, 7, 5, 6, 6],
       [5, 4, 3, 2, 1, 8, 9, 5, 9, 5]])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### 3.2.5 Dimension of an array

In [ ]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a.ndim

1

In [ ]:
b = np.array([[6,7,5,6,6], [8,9,5,9,5]])
b.ndim

2

In [ ]:
a = np.array([[[1,2,3,4], [4,5,6,7]], [[3,2,1,4],[6,5,4,1]], [[7,8,9,0],[9,8,7,6]]])
a.ndim

3

### 3.2.6 Number of elements in an array

In [ ]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a.size

10

In [ ]:
b = np.array([[6,7,5,6,6,6], [8,9,5,9,5,7]])
b.size

12

In [ ]:
a = np.array([[[1,2,3,4], [4,5,6,7]], [[3,2,1,4],[6,5,4,1]], [[7,8,9,0],[9,8,7,6]]])
a.size

24

### 3.2.7 Shape of an array

In [ ]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [ ]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a.shape
# Output: 10 Rows or Columns

(10,)

In [ ]:
b = np.array([[6,7,5,6,6,6], [8,9,5,9,5,7], [8,9,5,9,5,7]])
b
b

array([[6, 7, 5, 6, 6, 6],
       [8, 9, 5, 9, 5, 7],
       [8, 9, 5, 9, 5, 7]])

In [ ]:
b = np.array([[6,7,5,6,6,6], [8,9,5,9,5,7], [8,9,5,9,5,7]])
b
b.shape
# Output: 3 Rows, 6 Columns

(3, 6)

In [ ]:
a = np.array([[[1,2,3,4], [4,5,6,7]], [[3,2,1,4],[6,5,4,1]], [[7,8,9,0],[9,8,7,6]], [[3,2,1,4],[6,5,4,1]]])
a

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[3, 2, 1, 4],
        [6, 5, 4, 1]],

       [[7, 8, 9, 0],
        [9, 8, 7, 6]],

       [[3, 2, 1, 4],
        [6, 5, 4, 1]]])

In [ ]:
a = np.array([[[1,2,3,4], [4,5,6,7]], [[3,2,1,4],[6,5,4,1]], [[7,8,9,0],[9,8,7,6]], [[3,2,1,4],[6,5,4,1]]])
a.shape
# Output: 4 Layers, 2 Rows, 4 Columns

(4, 2, 4)

### 3.2.8 Reshaping an array

In [ ]:
a = np.arange(9) # 3*3 = 9
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a.reshape(3,3) 
# Can ony reshape it into multiple of 9 e.g. 3*3 = 9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.reshape(a, newshape=(1,9), order = "C")

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

### 3.2.9 Conversion of an Array

> Conversion of 1-D array to 2-D array

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

> Row wise 1D to 2D conversion 

In [ ]:
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
b.shape

(1, 9)

> Column wise 1D to 2D conversion

In [ ]:
c = a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
c.shape

(9, 1)

> Conversion of 1-D array to 2-D and then 2-D to 3-D
> 
> _Using np.newaxis will increase the dimensions of your array by one dimension when used once._

In [ ]:
a = np.arange(7)
a.shape


(7,)

In [ ]:
b = a[np.newaxis, :]
b.shape

(1, 7)

In [ ]:
c = b[np.newaxis, :]
c.shape

(1, 1, 7)

>Converting 1-D array to 2-D array at specific axis
>
>_You can also expand an array by inserting a new axis at a specified position with np.expand_dims._

In [ ]:
a = np.arange(6)
a.shape

(6,)

> You can use np.expand_dims to add an axis at index position 1

In [ ]:
b = np.expand_dims(a, axis=1)
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
b.shape

(6, 1)

>You can add an axis at index position 0


In [ ]:
b = np.expand_dims(a, axis=0)
b

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
b.shape

(1, 6)

### 3.2.10 Basic Arithmetic Operations on an Array

> Addition & Multiplication to elements of array

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [ ]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# Sum of elements
a.sum()

45

In [ ]:
# mean of elements
a.mean()

5.0

### 3.2.11 Indexing and Slicing

In [ ]:
a = np.array([10, 11, 12, 13, 14, 15])
a

array([10, 11, 12, 13, 14, 15])

In [ ]:
a[2]

12

In [ ]:
a[0:3]

array([10, 11, 12])

In [ ]:
a[0:]

array([10, 11, 12, 13, 14, 15])

In [ ]:
a[:5]

array([10, 11, 12, 13, 14])

In [ ]:
a[-5:]

array([11, 12, 13, 14, 15])

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[a<5]

array([1, 2, 3, 4])

In [ ]:
b = a > 5
a[b]

array([ 6,  7,  8,  9, 10, 11, 12])

In [ ]:
c = a[(a>2) & (a<10)]
c

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
c = (a>4) | (a==1)
c

array([[ True, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
b = np.nonzero(a <5)
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

> Slicing

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

> Slicing a row of an array
> 
> "1" is the index of the row of an array

In [ ]:
b = a[1, :]   # "1" is the index of the row of an array
b

array([5, 6, 7, 8])

> Slicing a Column of an array
> 
> "1" is the index of the Column of an array

In [ ]:
# to slice a column of an array
b = a[:, 1] # "1" is the index of the column of an array
b

array([ 2,  6, 10])

> slicing and modifying element

In [ ]:
b[0] = 200
b

array([200,   6,  10])

In [ ]:
a

array([[  1, 200,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

>Making a copy of an array


In [ ]:
c = a.copy()
c

array([[  1, 200,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

### 3.2.12: Array Stacking & Splitting

>You can stack them vertically with vstack

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))  

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

>Or stack them horizontally with hstack


In [ ]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

>Array Splitting

In [ ]:
x = np.arange(1, 25).reshape(3,8)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

>If you want to split this array into equally shaped arrays
>
> **Imp Note: Row or Column should be multiple of Row or Column, e.g. above array has 8 column it multiple could be 2, 4, 8)**

In [ ]:
np.hsplit(x,2)

[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24]])]

In [ ]:
np.hsplit(x, (5,6))

[array([[ 1,  2,  3,  4,  5],
        [ 9, 10, 11, 12, 13],
        [17, 18, 19, 20, 21]]),
 array([[ 6],
        [14],
        [22]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24]])]

## Section 3.3: Basic Array Operations

> Addition

In [ ]:
import numpy as np
a = np.array([2,3])
a

array([2, 3])

In [ ]:
b = np.ones(2, dtype=int)
b

array([1, 1])

In [ ]:
c = a+b
c

array([3, 4])

### 3.3.1 Basic Operations of 2D Array (Addition, Subtraction, Multiplication & Division) 

> You can add and multiply them using arithmetic operators if you have two matrices that are the same size.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])
a + b

array([[2, 3],
       [4, 5]])

> You can do these arithmetic operations on matrices of different sizes, but only if one matrix has only one column or one row.

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([[1, 1]])
x+y

array([[2, 3],
       [4, 5],
       [6, 7]])

>Subtraction

In [ ]:
d = a-b
d

array([1, 2])

> Multiplication

In [ ]:
e = c*d
e

array([[ 0,  4],
       [ 6, 12]])

> Division


In [ ]:
f = c/d
f

array([3., 2.])

### 3.3.2 Sum of Elements in Array

>Sum of elements in 1-D array

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a.sum()

6

>Sum of elements in 2-D array

In [ ]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

>sum of 2D array on 0 axis

In [ ]:
a.sum(axis = 0)

array([4, 6])

>sum of 2D array on 1 axis

In [ ]:
a.sum(axis = 1)

array([3, 7])

>multiplication of an scalar and vector in array

In [ ]:
a = np.array([1.5, 2.5])
a * 2

array([3., 5.])

## Section 3.4: Basic Statistical Operations in Arrays
> To find out maximum and minimum, sum, mean, product, standard deviation

> 1-D Array

In [ ]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.min()

1

In [ ]:
a.max()

9

In [ ]:
a.sum()

45

In [ ]:
a.prod()

362880

In [ ]:
a.std()

2.581988897471611

> 2-D Array

In [ ]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum()

4.8595784

In [ ]:
a.sort()
a

array([[0.17296777, 0.34376245, 0.45053314, 0.5510652 ],
       [0.05093587, 0.40067661, 0.54627315, 0.55645993],
       [0.12697628, 0.26590556, 0.56917101, 0.82485143]])

In [ ]:
a.min()

0.05093587

In [ ]:
a.max()

0.82485143

> Minimum and Maximum in 2-D Array at specific axis

> when we use axis=0 to specify the axis. it takes minimum value from each column
> 
> **Imp: axis = 0 gives output as row but scan in vertical way to find minimum value**

In [ ]:
a.min(axis=0)

array([0.05093587, 0.26590556, 0.45053314, 0.5510652 ])

>when we use axis=1 to specify the axis. it takes minimum value from each row
>
>**Imp: axis = 1 gives output as column but scan in horizontal way to find minimum value**

In [ ]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

> when we use axis=0 to specify the axis. it takes maximum value from each column
> 
> **Imp: axis = 0 gives output as row but scan in vertical way to find maximum value**

In [ ]:
a.max(axis=0)

array([0.17296777, 0.40067661, 0.56917101, 0.82485143])

> when we use axis=1 to specify the axis. it takes maximum value from each row
> 
> **Imp: axis = 1 gives output as column but scan in horizontal way to find maximum value**

In [ ]:
a.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [ ]:
a.prod()

1.451721612088471e-06

In [ ]:
a.std()

0.21392120766089617

## Section 3.5: Indexing 2-D Array

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

> In two dimensional array index (0, 1) here (Row = 0, Column = 1), Index will be the intersecting point of both Row and Column

In [ ]:
x[0 , 1]

2

> In 2-D array index (1:3, 1) or ((1,2), 1) here (Row, Column), Index will be the intersecting point of both Row and Column

In [ ]:
x[1:3, 1]

array([4, 6])

> In 2-D array index (1:3) or ((1,2), empty) here (Row = 1,2, Column = empty), Index will be on Row 1 & 2

In [ ]:
x[1:3]

array([[3, 4],
       [5, 6]])

> Maximum and Minimum in 2-D Array

In [ ]:
x.max()

6

In [ ]:
x.min()

1

> when we use axis=0 to specify the axis. it takes maximum value from each column
> 
> **Imp: axis = 0 gives output as row but scan in vertical way to find maximum value**


In [ ]:
x.max(axis=0)

array([5, 6])

> when we use axis=1 to specify the axis. it takes maximum value from each row
> 
> **Imp: axis = 1 gives output as column but scan in horizontal way to find maximum value**

In [ ]:
x.max(axis=1)

array([2, 4, 6])

> aggregate matrices the same way you aggregated vectors

In [ ]:
x.sum()

21

## Section 3.6: Random, Rerverse, Reshape & Transpose of an Array

> the simplest way to generate random numbers

In [ ]:
r = np.random.default_rng(0)
r.random(5)

array([0.63696169, 0.26978671, 0.04097352, 0.01652764, 0.81327024])

> ones(), zeros(), and random() to create a 2D array

In [ ]:
a = np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
b = np.ones((3,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
r.random((4,5))

array([[0.91275558, 0.60663578, 0.72949656, 0.54362499, 0.93507242],
       [0.81585355, 0.0027385 , 0.85740428, 0.03358558, 0.72965545],
       [0.17565562, 0.86317892, 0.54146122, 0.29971189, 0.42268722],
       [0.02831967, 0.12428328, 0.67062441, 0.64718951, 0.61538511]])

> unique items in 1D array (non-repetative items)

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
b = np.unique(a)
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

> Indices of unique values in the original array

In [ ]:
b = np.unique(a, return_index = True)
b

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

> Frequency count of unique values in a NumPy array

In [ ]:
b = np.unique(a, return_counts = True)
b

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64))

> unique items in 2D array

In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
b_2d = np.unique(a_2d)
b_2d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b_2d = np.unique(a_2d, return_index = True, return_counts = True)
b_2d

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64),
 array([2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

>Transposing and reshaping a matrix

In [ ]:
a = ([[1, 2, 3],
      [4, 5, 6]])
a

[[1, 2, 3], [4, 5, 6]]

In [ ]:
np.shape(a)

(2, 3)

In [ ]:
a = np.arange(6).reshape((2, 3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

> reverse an 1D array

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
b= np.flip(a)
b

array([8, 7, 6, 5, 4, 3, 2, 1])

> reverse an 2D array

In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b_2d = np.flip(a_2d)
b_2d

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

> reverse only the columns

In [ ]:
b_2d = np.flip(a_2d, axis = 0)
b_2d

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

> reverse only the rows

In [ ]:
b_2d = np.flip(a_2d, axis = 1)
b_2d

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

> reverse the contents of only one column or row

In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

> reverse the contents of the row at index position 1

In [ ]:
a_2d[1] = np.flip(a_2d[1])
a_2d

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

> reverse the contents of the column at index position 0

In [ ]:
a_2d[:,0] = np.flip(a_2d[:,0])
a_2d

array([[ 9,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 1, 10, 11, 12]])

## Section 3.7: Reshaping and Flattening Multidimensional Arrays

In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

>When you use flatten, changes to your new array won’t change the parent array

In [ ]:
x1 = x.flatten()
x1[1] = 22
x1

array([ 1, 22,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

> when you use ravel, the changes you make to the new array will affect the parent array.

In [ ]:
x1 = x.ravel()
x1[1] = 25
x1

array([ 1, 25,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
x

array([[ 1, 25,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

-----------------
-----------------